improve gh action

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,9 +1,11 @@
-name: Java CI with Gradle on master Commit
+# This workflow must be manually triggered. It accepts a version and a release type.
+# First it sets the version in gradle.properties to the new version and pushes it.
+# Then it generates a log, based on commits.
+# After that builds a jar and uploads it to curseforge/modrinth/GitHub releases
+
+name: Publish mod version
 
 on:
-  push:
-    tags:
-      - v*
   workflow_dispatch:
     inputs:
       tag_version:
@@ -17,42 +19,51 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    permissions:
+      # Give the default GITHUB_TOKEN write permission to commit and push the
+      # added or changed files to the repository.
+      contents: write
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Set Tag Version
-        id: tag_version
+      - name: Check if tag already exists
         run: |
-          if [[ ${{ github.ref }} == refs/tags/* ]]; then
-            tag=${{ github.ref }}
-            tag=${tag/refs\/tags\//}
-            tag=${tag//v/}
-            tag_message=$(git tag -l --format='%(contents)' "${tag}")
-            echo "::set-output name=version::${tag}"
-            echo "::set-output name=release_type::${tag_message}"
-          elif [[ -n "${{ github.event.inputs.tag_version }}" ]]; then
-            echo "::set-output name=version::${{ github.event.inputs.tag_version }}"
-            echo "::set-output name=release_type::${{ github.event.inputs.release_type }}"
+          if git rev-parse --verify --quiet "v${{ github.event.inputs.version }}"; then
+            echo "Version ${{ github.event.inputs.version }} already exists, aborting workflow."
+            exit 1
           fi
+        env:
+
+      - name: Set version
+        run: sed -i "s/mod_version=.*/mod_version=${{ github.event.inputs.version }}/g" gradle.properties
+
+      - name: Commit and push gradle.properties
+        uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          commit_message: "Bump version to ${{ github.event.inputs.version }}"
+          commit_options: "--no-verify"
+          file_pattern: gradle.properties
+          tagging_message: "v${{ github.event.inputs.version }}"
 
       - name: Generate Changelog
         run: |
-          echo "## Changelog v${{ steps.tag_version.outputs.version }}-${{ steps.tag_version.outputs.release_type }}" > CHANGELOG.md
+          echo "### Changelog ${{ github.event.inputs.version }}-${{ github.event.inputs.release-type }}" > CHANGELOG.md
           if git describe --tags --abbrev=0 > /dev/null 2>&1; then
             latest_tag=$(git describe --tags --abbrev=0)
             previous_tag=$(git describe --tags --abbrev=0 ${latest_tag}^)
             changelog=$(git log --pretty=format:'- %s' --oneline --decorate --decorate-refs=0 ${previous_tag}..${latest_tag})
             echo "${changelog}" >> CHANGELOG.md
           else
-            echo "No tags found" >> CHANGELOG.md
+            echo "- No tags found" >> CHANGELOG.md
           fi
 
-      - name: Set up JDK 8
-        uses: actions/setup-java@v2
+      - name: Setup Java
+        uses: actions/setup-java@v3
         with:
+          distribution: 'temurin'
           java-version: '8'
-          distribution: 'adopt'
+
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
       - name: Build with Gradle
@@ -63,17 +74,37 @@ jobs:
         with:
           curseforge-id: 687577
           curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
+
+          github-tag: "v${{ steps.tag_version.outputs.version }}"
+          github-generate-changelog: true
+          github-draft: false
+          github-prerelease: false
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+
           files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
           files-secondary: build/libs/*-@(dev|sources|javadoc).jar
-          name: GroovyScript-${{ steps.tag_version.outputs.version }}
-          version: ${{ steps.tag_version.outputs.version }}
-          version-type: ${{ steps.tag_version.outputs.release_type }}
+          name: GroovyScript-${{ github.event.inputs.tag_version }}
+          version: ${{ github.event.inputs.tag_version }}
+          version-type: ${{ github.event.inputs.release_type }}
           changelog-file: CHANGELOG.md
           loaders: |
             forge
           game-versions: |
             1.12.2
           dependencies: |
+            mekanism | recommends | *
+            blood-magic | recommends | *
+            thermal-expansion | recommends | *
+            draconic-evolution | recommends | *
+            ender-io | recommends | *
+            industrial-craft | recommends | *
+            ic2-classic | recommends | *
+            astral-sorcery | recommends | *
+            thaumcraft | recommends | *
+            immersive-engineering | recommends | *
+            tinkers-construct | recommends | *
+            tinkers-complement | recommends | *
+            constructs-armory | recommends | *
           java: |
             8
           retry-attempts: 2
